# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call('_dhlvm_rcpp_hello_world', PACKAGE = 'dhlvm')
}

ldmultinom_cpp <- function(x, prob) {
    .Call('_dhlvm_ldmultinom_cpp', PACKAGE = 'dhlvm', x, prob)
}

rdirichlet_cpp <- function(alpha_m) {
    .Call('_dhlvm_rdirichlet_cpp', PACKAGE = 'dhlvm', alpha_m)
}

timesTwo <- function(x) {
    .Call('_dhlvm_timesTwo', PACKAGE = 'dhlvm', x)
}

sampleState_cpp <- function(data, P, S_prev, beta) {
    .Call('_dhlvm_sampleState_cpp', PACKAGE = 'dhlvm', data, P, S_prev, beta)
}

sampleTransition_cpp <- function(S, alpha) {
    .Call('_dhlvm_sampleTransition_cpp', PACKAGE = 'dhlvm', S, alpha)
}

sampleBeta_cpp <- function(data, S, eta) {
    .Call('_dhlvm_sampleBeta_cpp', PACKAGE = 'dhlvm', data, S, eta)
}

