# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sampleZ <- function(data, theta, beta) {
    .Call(`_dhlvm_sampleZ`, data, theta, beta)
}

sampleSigma <- function(gamma, v0, s0) {
    .Call(`_dhlvm_sampleSigma`, gamma, v0, s0)
}

sampleGamma <- function(z, sigma, gammaprev, shrink) {
    .Call(`_dhlvm_sampleGamma`, z, sigma, gammaprev, shrink)
}

sampleBetaLDA <- function(data, z, eta) {
    .Call(`_dhlvm_sampleBetaLDA`, data, z, eta)
}

discreteLDS_cpp <- function(data, eta, v0, s0, tune, K, V, steps) {
    .Call(`_dhlvm_discreteLDS_cpp`, data, eta, v0, s0, tune, K, V, steps)
}

discreteMS_cpp <- function(data, eta, alpha, K, steps) {
    .Call(`_dhlvm_discreteMS_cpp`, data, eta, alpha, K, steps)
}

testRgamma <- function(v0, s0) {
    .Call(`_dhlvm_testRgamma`, v0, s0)
}

