# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

posteriorLikelihood <- function(data, groups, pi, beta) {
    .Call(`_dhlvm_posteriorLikelihood`, data, groups, pi, beta)
}

hlc_cpp_noZ <- function(data, groups, eta, alpha, steps) {
    .Call(`_dhlvm_hlc_cpp_noZ`, data, groups, eta, alpha, steps)
}

hlc_cpp <- function(data, groups, eta, alpha, steps) {
    .Call(`_dhlvm_hlc_cpp`, data, groups, eta, alpha, steps)
}

dhlc_cpp_noZ <- function(data, groups, eta, v0, s0, tune, K, T, steps) {
    .Call(`_dhlvm_dhlc_cpp_noZ`, data, groups, eta, v0, s0, tune, K, T, steps)
}

dhlc_cpp <- function(data, groups, eta, v0, s0, tune, K, T, steps) {
    .Call(`_dhlvm_dhlc_cpp`, data, groups, eta, v0, s0, tune, K, T, steps)
}

sampleZ_old <- function(data, theta, beta) {
    .Call(`_dhlvm_sampleZ_old`, data, theta, beta)
}

sampleGamma_old <- function(z, sigma, gammaprev, shrink) {
    .Call(`_dhlvm_sampleGamma_old`, z, sigma, gammaprev, shrink)
}

sampleBetaLDA <- function(data, z, eta) {
    .Call(`_dhlvm_sampleBetaLDA`, data, z, eta)
}

discreteLDS_cpp <- function(data, eta, v0, s0, tune, K, V, steps) {
    .Call(`_dhlvm_discreteLDS_cpp`, data, eta, v0, s0, tune, K, V, steps)
}

discreteMS_cpp <- function(data, eta, alpha, K, steps) {
    .Call(`_dhlvm_discreteMS_cpp`, data, eta, alpha, K, steps)
}

testRgamma <- function(v0, s0) {
    .Call(`_dhlvm_testRgamma`, v0, s0)
}

